version: "3.9"

services:
    client:
        depends_on:
            - server
        build: ./
        ports:
            - 80:80

    server:
        depends_on:
            - db
        build: ./server
        ports:
            - 4000:4000
        environment:
            MONGO_URI: mongodb://db/feedbacks

    db:
        image: mongo:4.0.16-xenial
        ports:
            - 27017:27017
        volumes:
            - feedbacks:/data/db

volumes:
    feedbacks:
